---

uwpoash-error-forbidden:
  path: /error/forbidden
  defaults: {
    _controller: 'SimpleSAML\Module\uwpoash\Controller\Authorize::forbidden'
  }
  methods: [GET]
uwpoash-reauthenticate:
  path: /error/reauthenticate
  defaults: {
    _controller: 'SimpleSAML\Module\uwpoash\Controller\Authorize::reauthenticate'
  }
  methods: [GET]
